### ISSUE TITLE
Firebase Auth

### ISSUE THREAD

**Issue by listingslab** [seedscanner/seedscanner#7]
- Implement Firebase Auth Solution
- Users managed here https://console.firebase.google.com/u/0/project/seedscanner-manager/authentication/users

### hints
https://github.com/seedscanner/manager/blob/master/src/components/LoginForm.jsx

### Bounty 
1 monkey

**Comment by listingslab** [comment]
open to offers

**Comment by deutscher-chris** [comment]
branch `issues/7/firebase-auth`

**Comment by dongido001** [comment]
Still open? @listingslab

**Comment by weizang-75** [comment]
> Still open? @listingslab

all done, brohiem @dongido001
